### ISSUE TITLE
Loading CSS files

### ISSUE THREAD

**Issue by pYr0x** [requirejs/almond#120]
is it possible to load CSS files and append them to the document?

**Comment by jrburke** [comment]
almond provides an AMD API for built resources that are bundled into one JS file, so it cannot do any loading of external items. If there is a [loader plugin](https://github.com/requirejs/requirejs/wiki/Plugins) that implements the build APIs that the r.js optimizer calls, then it could be possible for that loader plugin to inline resources that, in the case of CSS, could attach some <style> tags to the DOM with inline CSS. I think it would be hard to work out external resources, like images, referenced by the built file though.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by pYr0x** [comment]
@jrburke thanks.
i wrote a simple css plugin thats `load` method append the css-file to the document.
it is working, but!: we used systemJS so our require-calls are `module!plugin` but requireJS has `plugin!module`, do you know any way to load the plugin with the wrong order?

**Comment by jrburke** [comment]
Probably the best way to do that is to have a post build process that just does a regexp replacement of the IDs to reverse the order.
