### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by sebcante** [requirejs/almond#40]
Hi james,

I am migrating to require 2.0 and using almond. I have a couple of shim configured it is working fine when using require.js but after minification (using almond instead of require.js) it seems that something is missing : 

error : Uncaught ReferenceError: exports is not defined
getGlobal does not seem exist.

here is the code created as build time

``` javascript
define("backbone", ["underscore","jquery"], (function (global) {
    return function () {
        var func = function () {

                            return getGlobal(exports); <-- Uncaught ReferenceError: exports is not defined

                        };
        return func.apply(global, arguments);
    }
}(this)));
```

This example uses the following shim 

``` javascript
   shim:{
        'backbone': {
            //These script dependencies should be loaded before loading
            //backbone.js
            deps: ['underscore', 'jquery'],
            //Once loaded, use the global 'Backbone' as the
            //module value.
            exports: 'Backbone'
        },   [...]
```

Version : 
r.js 2.0.6
almond 0.1.4

**Comment by amivit** [comment]
And the solution?
